pipeline:
  build:
    image: laradock/workspace:1.8-71
    group: laravel
    commands:
      - php -v
      - composer -V
      - cp .env.example .env
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan migrate
      - ./vendor/bin/phpunit
services:
  mysql:
    image: mysql
    ports:
      - 0.0.0.0:3307:33060
    environment:
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=secret
