pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./vendor
    volumes:
      - /tmp/cache:/cache
  test:
    image: laradock/workspace:1.8-71
    group: laravel
    commands:
      - php -v
      - pwd
      - apt install net-tools
      - apt install curl
      - touch /drone/src/github.com/Wqrld/theta/database.sqlite
      - composer -V
      - cp .env.example .env
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan migrate
      - php artisan serve  --host=0.0.0.0 --port=80 &
      - sleep 5
      - netstat -lvnp
      - curl 127.0.0.1
      - ./vendor/bin/phpunit --verbose
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./vendor
    volumes:
      - /tmp/cache:/cache
