pipeline:
  build:
    image: laradock/workspace:1.8-71
    group: laravel
    commands:
      - php -v
      - pwd
      - touch /drone/src/github.com/Wqrld/theta/database.sqlite
      - composer -V
      - cp .env.example .env
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan migrate
